global:
  scrape_interval: 30s

scrape_configs:
  - job_name: 'django'
    static_configs:
      - targets: ['web:8000']
    metrics_path: '/metrics'

  - job_name: 'celery'
    static_configs:
      - targets: ['celery:8888']
    metrics_path: '/metrics'
