# Generated by Django 5.2.4 on 2025-07-27 22:45

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='textsubmission',
            name='text_hash',
            field=models.CharField(default='', max_length=64, unique=True),
            preserve_default=False,
        ),
    ]
