# Generated by Django 5.2.4 on 2025-08-09 00:32

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('core', '0002_textsubmission_text_hash'),
    ]

    operations = [
        migrations.AddField(
            model_name='textsubmission',
            name='indexed_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
