# Generated by Django 5.2.4 on 2025-08-09 00:52

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('core', '0003_textsubmission_indexed_at'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='textsubmission',
            index=models.Index(
                condition=models.Q(('indexed_at__isnull', True)),
                fields=['indexed_at'],
                name='idx_unindexed',
            ),
        ),
    ]
